export const seedProducts = [
  {
    id: "prod-desk-mat",
    slug: "jeongseok-desk-mat",
    name: "정석 데스크 매트",
    category: "DESK",
    shortDescription: "책상 위 기준선을 잡아주는 와이드 데스크 매트",
    description: "노트북과 키보드, 필기 공간을 하나의 작업 구역으로 정리하는 900mm 와이드 데스크 매트입니다.",
    price: 49000,
    compareAtPrice: 59000,
    stock: 36,
    featured: true,
    accent: "#0047ff",
  },
  {
    id: "prod-laptop-stand",
    slug: "jeongseok-laptop-stand",
    name: "정석 노트북 스탠드",
    category: "DESK",
    shortDescription: "시선 높이를 단단하게 고정하는 알루미늄 스탠드",
    description: "11~16인치 노트북을 위한 각도 조절형 알루미늄 스탠드입니다.",
    price: 79000,
    compareAtPrice: null,
    stock: 18,
    featured: true,
    accent: "#ff5c35",
  },
  {
    id: "prod-desk-organizer",
    slug: "jeongseok-desk-organizer",
    name: "정석 모듈 오거나이저",
    category: "DESK",
    shortDescription: "작은 도구의 자리를 바꿔 쓰는 모듈형 트레이",
    description: "펜·메모지·케이블을 사용 습관에 맞춰 재배치하는 세 개의 모듈로 구성됩니다.",
    price: 39000,
    compareAtPrice: null,
    stock: 42,
    featured: false,
    accent: "#7c3cff",
  },
  {
    id: "prod-charging-station",
    slug: "jeongseok-charging-station",
    name: "정석 3-in-1 충전 스테이션",
    category: "MOBILE",
    shortDescription: "휴대폰·워치·이어폰을 한 자리에 두는 충전 베이스",
    description: "Qi2 호환 기기와 스마트워치, 무선 이어폰을 동시에 정리하는 데스크 충전 스테이션입니다.",
    price: 129000,
    compareAtPrice: 149000,
    stock: 14,
    featured: true,
    accent: "#00a878",
  },
  {
    id: "prod-phone-stand",
    slug: "jeongseok-folding-phone-stand",
    name: "정석 폴딩 폰 스탠드",
    category: "MOBILE",
    shortDescription: "가방에 넣고 다니는 접이식 화면 거치대",
    description: "영상 통화와 보조 화면 사용을 위한 높이·각도 조절형 휴대폰 스탠드입니다.",
    price: 29000,
    compareAtPrice: null,
    stock: 58,
    featured: false,
    accent: "#ffb800",
  },
  {
    id: "prod-cable-kit",
    slug: "jeongseok-cable-kit",
    name: "정석 케이블 키트",
    category: "MOBILE",
    shortDescription: "자주 쓰는 충전 규격을 한 파우치에 모은 세트",
    description: "USB-C 중심의 짧은 케이블과 변환 젠더를 한 파우치에 구성한 휴대용 키트입니다.",
    price: 35000,
    compareAtPrice: null,
    stock: 64,
    featured: false,
    accent: "#e94f8a",
  },
  {
    id: "prod-timer-cube",
    slug: "jeongseok-timer-cube",
    name: "정석 타이머 큐브",
    category: "FOCUS",
    shortDescription: "뒤집는 즉시 시작되는 집중 타이머",
    description: "5·15·30·50분 면을 위로 돌리면 바로 카운트다운이 시작되는 물리 타이머입니다.",
    price: 32000,
    compareAtPrice: 39000,
    stock: 27,
    featured: true,
    accent: "#ff3d71",
  },
  {
    id: "prod-earplugs",
    slug: "jeongseok-focus-earplugs",
    name: "정석 포커스 이어플러그",
    category: "FOCUS",
    shortDescription: "공부와 이동 중 주변 소음을 줄이는 재사용 이어플러그",
    description: "일상 소음을 완화하는 실리콘 이어플러그와 세 가지 크기의 팁 세트입니다.",
    price: 24000,
    compareAtPrice: null,
    stock: 73,
    featured: false,
    accent: "#635bff",
  },
  {
    id: "prod-focus-notes",
    slug: "jeongseok-focus-notes",
    name: "정석 포커스 노트",
    category: "FOCUS",
    shortDescription: "오늘 끝낼 한 가지를 먼저 쓰는 90일 노트",
    description: "우선순위 한 개와 시간 블록, 회고를 한 면에서 관리하는 90일 작업 노트입니다.",
    price: 18000,
    compareAtPrice: null,
    stock: 91,
    featured: false,
    accent: "#1e293b",
  },
  {
    id: "prod-tech-pouch",
    slug: "jeongseok-tech-pouch",
    name: "정석 테크 파우치",
    category: "TRAVEL",
    shortDescription: "충전기와 케이블을 펼쳐서 찾는 슬림 파우치",
    description: "양쪽으로 완전히 열려 이동 중 필요한 도구를 한눈에 찾는 생활 방수 파우치입니다.",
    price: 45000,
    compareAtPrice: 52000,
    stock: 33,
    featured: true,
    accent: "#0ea5e9",
  },
  {
    id: "prod-travel-charger",
    slug: "jeongseok-travel-charger",
    name: "정석 슬림 멀티 충전기",
    category: "TRAVEL",
    shortDescription: "노트북과 휴대폰을 함께 충전하는 100W 어댑터",
    description: "USB-C 3개와 USB-A 1개 포트를 제공하는 GaN 기반 100W 멀티 충전기입니다.",
    price: 89000,
    compareAtPrice: 99000,
    stock: 22,
    featured: true,
    accent: "#f97316",
  },
  {
    id: "prod-cable-tag",
    slug: "jeongseok-cable-tags",
    name: "정석 케이블 태그",
    category: "TRAVEL",
    shortDescription: "케이블의 용도와 소유자를 바로 찾는 태그 세트",
    description: "지우고 다시 쓸 수 있는 라벨 면을 가진 실리콘 케이블 태그 12개 세트입니다.",
    price: 12000,
    compareAtPrice: null,
    stock: 120,
    featured: false,
    accent: "#14b8a6",
  },
] as const;

export const seedFacts = [
  ["prod-desk-mat", "size", "900 × 400mm", "제품 규격서 v1"],
  ["prod-desk-mat", "material", "비건 레더 상판·미끄럼 방지 바닥", "제품 규격서 v1"],
  ["prod-laptop-stand", "compatibility", "11~16인치, 최대 5kg", "제품 규격서 v1"],
  ["prod-charging-station", "compatibility", "Qi2 호환 휴대폰·워치·무선 이어폰", "호환표 v1"],
  ["prod-timer-cube", "preset", "5·15·30·50분", "제품 규격서 v1"],
  ["prod-travel-charger", "power", "최대 합산 100W", "전력 사양서 v1"],
] as const;
